/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results     
 *
 * OpenAPI spec version: v2.75.0
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kisio.NavitiaSDK.apis;

import org.kisio.NavitiaSDK.invokers.ApiCallback;
import org.kisio.NavitiaSDK.invokers.ApiException;
import java.math.BigDecimal;
import org.joda.time.DateTime;
import org.kisio.NavitiaSDK.models.LineGroups;
import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LineGroupsApiTest {
    private final String testToken = "47e2c935-7635-42ec-934c-cc582eaa04b6";

    // LineGroupsApi constructor
    @Test
    public void shouldInstantiateLineGroupsApiGivenValidToken() throws Exception {
        LineGroupsApi currentApi = new LineGroupsApi(testToken);

        assertNotNull(currentApi);
    }

    @Test
    public void shouldNotInstantiateLineGroupsApiGivenValidToken() throws Exception {
        LineGroupsApi currentApi = null;

        try {
            currentApi = new LineGroupsApi("");
        } catch (Exception e) {
            assertEquals("Navitia token cannot be empty", e.getMessage());
        }

        assertNull(currentApi);
    }
    
        @Test
@Ignore
public void CoverageLonLatLineGroupsRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageLonLatLineGroupsIdRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageLonLatUriLineGroupsRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageLonLatUriLineGroupsIdRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageRegionLineGroupsRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageRegionLineGroupsIdRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageRegionUriLineGroupsRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageRegionUriLineGroupsIdRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void LineGroupsRequestBuilder_get_Test() {}

    
}
