/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results     
 *
 * OpenAPI spec version: v2.78.0
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kisio.NavitiaSDK.apis;

import org.kisio.NavitiaSDK.invokers.ApiCallback;
import org.kisio.NavitiaSDK.invokers.ApiException;
import java.math.BigDecimal;
import org.kisio.NavitiaSDK.models.TrafficReports;
import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TrafficReportApiTest {
    private final String testToken = "fc4b8d9e-ca2e-487f-9c04-c81fc9d2a781";

    // TrafficReportApi constructor
    @Test
    public void shouldInstantiateTrafficReportApiGivenValidToken() throws Exception {
        TrafficReportApi currentApi = new TrafficReportApi(testToken);

        assertNotNull(currentApi);
    }

    @Test
    public void shouldNotInstantiateTrafficReportApiGivenValidToken() throws Exception {
        TrafficReportApi currentApi = null;

        try {
            currentApi = new TrafficReportApi("");
        } catch (Exception e) {
            assertEquals("Navitia token cannot be empty", e.getMessage());
        }

        assertNull(currentApi);
    }
    
        @Test
@Ignore
public void CoverageLonLatTrafficReportsRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageLonLatUriTrafficReportsRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageRegionTrafficReportsRequestBuilder_get_Test() {}

    
        @Test
@Ignore
public void CoverageRegionUriTrafficReportsRequestBuilder_get_Test() {}

    
}
