/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results     
 *
 * OpenAPI spec version: v2.43.0-34-g30b0bcf
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kisio.NavitiaSDK.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.kisio.NavitiaSDK.models.Coverage;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * Coverages
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.NavitiaSDKJavaClientCodegen", date = "2017-11-03T11:50:27.015+01:00")
public class Coverages implements Parcelable {
  @SerializedName("regions")
  private List<Coverage> regions = new ArrayList<Coverage>();

  public Coverages regions(List<Coverage> regions) {
    this.regions = regions;
    return this;
  }

  public Coverages addRegionsItem(Coverage regionsItem) {
    this.regions.add(regionsItem);
    return this;
  }

   /**
   * Get regions
   * @return regions
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Coverage> getRegions() {
    return regions;
  }

  public void setRegions(List<Coverage> regions) {
    this.regions = regions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Coverages coverages = (Coverages) o;
    return Objects.equals(this.regions, coverages.regions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(regions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Coverages {\n");
    
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
  public void writeToParcel(Parcel out, int flags) {
     
    out.writeValue(regions);
  }

  public Coverages() {
    super();
  }

  Coverages(Parcel in) {
    
    regions = (List<Coverage>)in.readValue(Coverage.class.getClassLoader());
  }
  
  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<Coverages> CREATOR = new Parcelable.Creator<Coverages>() {
    public Coverages createFromParcel(Parcel in) {
      return new Coverages(in);
    }
    public Coverages[] newArray(int size) {
      return new Coverages[size];
    }
  };
}

