/*
 * navitia
 *      navitia.io is the open API for building cool stuff with mobility data. It provides the following services      * journeys computation     * line schedules     * next departures     * exploration of public transport data / search places     * and sexy things such as isochrones      navitia is a HATEOAS API that returns JSON formated results     
 *
 * OpenAPI spec version: v2.38.0
 * Contact: navitia@googlegroups.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kisio.NavitiaSDK.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.kisio.NavitiaSDK.models.JourneyPatternPoint;
import org.kisio.NavitiaSDK.models.StopPoint;

/**
 * StopTime
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.NavitiaSDKJavaClientCodegen", date = "2017-09-11T17:13:37.346+02:00")
public class StopTime {
  @SerializedName("stop_point")
  private StopPoint stopPoint = null;

  @SerializedName("headsign")
  private String headsign = null;

  @SerializedName("journey_pattern_point")
  private JourneyPatternPoint journeyPatternPoint = null;

  @SerializedName("departure_time")
  private String departureTime = null;

  @SerializedName("arrival_time")
  private String arrivalTime = null;

  public StopTime stopPoint(StopPoint stopPoint) {
    this.stopPoint = stopPoint;
    return this;
  }

   /**
   * Get stopPoint
   * @return stopPoint
  **/
  @ApiModelProperty(value = "")
  public StopPoint getStopPoint() {
    return stopPoint;
  }

  public void setStopPoint(StopPoint stopPoint) {
    this.stopPoint = stopPoint;
  }

  public StopTime headsign(String headsign) {
    this.headsign = headsign;
    return this;
  }

   /**
   * Get headsign
   * @return headsign
  **/
  @ApiModelProperty(value = "")
  public String getHeadsign() {
    return headsign;
  }

  public void setHeadsign(String headsign) {
    this.headsign = headsign;
  }

  public StopTime journeyPatternPoint(JourneyPatternPoint journeyPatternPoint) {
    this.journeyPatternPoint = journeyPatternPoint;
    return this;
  }

   /**
   * Get journeyPatternPoint
   * @return journeyPatternPoint
  **/
  @ApiModelProperty(value = "")
  public JourneyPatternPoint getJourneyPatternPoint() {
    return journeyPatternPoint;
  }

  public void setJourneyPatternPoint(JourneyPatternPoint journeyPatternPoint) {
    this.journeyPatternPoint = journeyPatternPoint;
  }

  public StopTime departureTime(String departureTime) {
    this.departureTime = departureTime;
    return this;
  }

   /**
   * Get departureTime
   * @return departureTime
  **/
  @ApiModelProperty(value = "")
  public String getDepartureTime() {
    return departureTime;
  }

  public void setDepartureTime(String departureTime) {
    this.departureTime = departureTime;
  }

  public StopTime arrivalTime(String arrivalTime) {
    this.arrivalTime = arrivalTime;
    return this;
  }

   /**
   * Get arrivalTime
   * @return arrivalTime
  **/
  @ApiModelProperty(value = "")
  public String getArrivalTime() {
    return arrivalTime;
  }

  public void setArrivalTime(String arrivalTime) {
    this.arrivalTime = arrivalTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StopTime stopTime = (StopTime) o;
    return Objects.equals(this.stopPoint, stopTime.stopPoint) &&
        Objects.equals(this.headsign, stopTime.headsign) &&
        Objects.equals(this.journeyPatternPoint, stopTime.journeyPatternPoint) &&
        Objects.equals(this.departureTime, stopTime.departureTime) &&
        Objects.equals(this.arrivalTime, stopTime.arrivalTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stopPoint, headsign, journeyPatternPoint, departureTime, arrivalTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StopTime {\n");
    
    sb.append("    stopPoint: ").append(toIndentedString(stopPoint)).append("\n");
    sb.append("    headsign: ").append(toIndentedString(headsign)).append("\n");
    sb.append("    journeyPatternPoint: ").append(toIndentedString(journeyPatternPoint)).append("\n");
    sb.append("    departureTime: ").append(toIndentedString(departureTime)).append("\n");
    sb.append("    arrivalTime: ").append(toIndentedString(arrivalTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

