package com.kisio.navitia.sdk.expert;

import com.kisio.navitia.sdk.expert.apis.AddressesApi;
import com.kisio.navitia.sdk.expert.apis.CalendarsApi;
import com.kisio.navitia.sdk.expert.apis.CommercialModesApi;
import com.kisio.navitia.sdk.expert.apis.CompaniesApi;
import com.kisio.navitia.sdk.expert.apis.ContributorsApi;
import com.kisio.navitia.sdk.expert.apis.CoordApi;
import com.kisio.navitia.sdk.expert.apis.CoordsApi;
import com.kisio.navitia.sdk.expert.apis.CoverageApi;
import com.kisio.navitia.sdk.expert.apis.DatasetsApi;
import com.kisio.navitia.sdk.expert.apis.DisruptionsApi;
import com.kisio.navitia.sdk.expert.apis.EquipmentReportsApi;
import com.kisio.navitia.sdk.expert.apis.GeoStatusApi;
import com.kisio.navitia.sdk.expert.apis.GraphicalIsochroneApi;
import com.kisio.navitia.sdk.expert.apis.HeatMapApi;
import com.kisio.navitia.sdk.expert.apis.JourneyPatternPointsApi;
import com.kisio.navitia.sdk.expert.apis.JourneyPatternsApi;
import com.kisio.navitia.sdk.expert.apis.JourneysApi;
import com.kisio.navitia.sdk.expert.apis.LineGroupsApi;
import com.kisio.navitia.sdk.expert.apis.LineReportsApi;
import com.kisio.navitia.sdk.expert.apis.LinesApi;
import com.kisio.navitia.sdk.expert.apis.NetworksApi;
import com.kisio.navitia.sdk.expert.apis.NextArrivalsApi;
import com.kisio.navitia.sdk.expert.apis.NextDeparturesApi;
import com.kisio.navitia.sdk.expert.apis.PhysicalModesApi;
import com.kisio.navitia.sdk.expert.apis.PlaceUriApi;
import com.kisio.navitia.sdk.expert.apis.PlacesApi;
import com.kisio.navitia.sdk.expert.apis.PlacesNearbyApi;
import com.kisio.navitia.sdk.expert.apis.PoiTypesApi;
import com.kisio.navitia.sdk.expert.apis.PoisApi;
import com.kisio.navitia.sdk.expert.apis.PtobjectsApi;
import com.kisio.navitia.sdk.expert.apis.RouteSchedulesApi;
import com.kisio.navitia.sdk.expert.apis.RoutesApi;
import com.kisio.navitia.sdk.expert.apis.StopAreasApi;
import com.kisio.navitia.sdk.expert.apis.StopPointsApi;
import com.kisio.navitia.sdk.expert.apis.StopSchedulesApi;
import com.kisio.navitia.sdk.expert.apis.TrafficReportApi;
import com.kisio.navitia.sdk.expert.apis.TripsApi;
import com.kisio.navitia.sdk.expert.apis.VehicleJourneysApi;

public class NavitiaSDK {
    public final AddressesApi addressesApi;
    public final CalendarsApi calendarsApi;
    public final CommercialModesApi commercialModesApi;
    public final CompaniesApi companiesApi;
    public final ContributorsApi contributorsApi;
    public final CoordApi coordApi;
    public final CoordsApi coordsApi;
    public final CoverageApi coverageApi;
    public final DatasetsApi datasetsApi;
    public final DisruptionsApi disruptionsApi;
    public final EquipmentReportsApi equipmentReportsApi;
    public final GeoStatusApi geoStatusApi;
    public final GraphicalIsochroneApi graphicalIsochroneApi;
    public final HeatMapApi heatMapApi;
    public final JourneyPatternPointsApi journeyPatternPointsApi;
    public final JourneyPatternsApi journeyPatternsApi;
    public final JourneysApi journeysApi;
    public final LineGroupsApi lineGroupsApi;
    public final LineReportsApi lineReportsApi;
    public final LinesApi linesApi;
    public final NetworksApi networksApi;
    public final NextArrivalsApi nextArrivalsApi;
    public final NextDeparturesApi nextDeparturesApi;
    public final PhysicalModesApi physicalModesApi;
    public final PlaceUriApi placeUriApi;
    public final PlacesApi placesApi;
    public final PlacesNearbyApi placesNearbyApi;
    public final PoiTypesApi poiTypesApi;
    public final PoisApi poisApi;
    public final PtobjectsApi ptobjectsApi;
    public final RouteSchedulesApi routeSchedulesApi;
    public final RoutesApi routesApi;
    public final StopAreasApi stopAreasApi;
    public final StopPointsApi stopPointsApi;
    public final StopSchedulesApi stopSchedulesApi;
    public final TrafficReportApi trafficReportApi;
    public final TripsApi tripsApi;
    public final VehicleJourneysApi vehicleJourneysApi;

    public NavitiaSDK(NavitiaConfiguration configuration) throws Exception {
        this.addressesApi = new AddressesApi(configuration.getToken());
        this.calendarsApi = new CalendarsApi(configuration.getToken());
        this.commercialModesApi = new CommercialModesApi(configuration.getToken());
        this.companiesApi = new CompaniesApi(configuration.getToken());
        this.contributorsApi = new ContributorsApi(configuration.getToken());
        this.coordApi = new CoordApi(configuration.getToken());
        this.coordsApi = new CoordsApi(configuration.getToken());
        this.coverageApi = new CoverageApi(configuration.getToken());
        this.datasetsApi = new DatasetsApi(configuration.getToken());
        this.disruptionsApi = new DisruptionsApi(configuration.getToken());
        this.equipmentReportsApi = new EquipmentReportsApi(configuration.getToken());
        this.geoStatusApi = new GeoStatusApi(configuration.getToken());
        this.graphicalIsochroneApi = new GraphicalIsochroneApi(configuration.getToken());
        this.heatMapApi = new HeatMapApi(configuration.getToken());
        this.journeyPatternPointsApi = new JourneyPatternPointsApi(configuration.getToken());
        this.journeyPatternsApi = new JourneyPatternsApi(configuration.getToken());
        this.journeysApi = new JourneysApi(configuration.getToken());
        this.lineGroupsApi = new LineGroupsApi(configuration.getToken());
        this.lineReportsApi = new LineReportsApi(configuration.getToken());
        this.linesApi = new LinesApi(configuration.getToken());
        this.networksApi = new NetworksApi(configuration.getToken());
        this.nextArrivalsApi = new NextArrivalsApi(configuration.getToken());
        this.nextDeparturesApi = new NextDeparturesApi(configuration.getToken());
        this.physicalModesApi = new PhysicalModesApi(configuration.getToken());
        this.placeUriApi = new PlaceUriApi(configuration.getToken());
        this.placesApi = new PlacesApi(configuration.getToken());
        this.placesNearbyApi = new PlacesNearbyApi(configuration.getToken());
        this.poiTypesApi = new PoiTypesApi(configuration.getToken());
        this.poisApi = new PoisApi(configuration.getToken());
        this.ptobjectsApi = new PtobjectsApi(configuration.getToken());
        this.routeSchedulesApi = new RouteSchedulesApi(configuration.getToken());
        this.routesApi = new RoutesApi(configuration.getToken());
        this.stopAreasApi = new StopAreasApi(configuration.getToken());
        this.stopPointsApi = new StopPointsApi(configuration.getToken());
        this.stopSchedulesApi = new StopSchedulesApi(configuration.getToken());
        this.trafficReportApi = new TrafficReportApi(configuration.getToken());
        this.tripsApi = new TripsApi(configuration.getToken());
        this.vehicleJourneysApi = new VehicleJourneysApi(configuration.getToken());
    }
}
